Lesson 19 mvc
DzmitryKhokha/js-hometasks-khokha pull request #14
Opened 2022-04-18 10:31 UTC by DzmitryKhokha

2022-04-21 20:15 UTC, instinct-it-academy approved these changes
Добрый вечер, задание пока что на доработку т.к. косвенно работает, но реализовано не корректно, обратите внимание на комментарии и пример выполнения

2022-04-21 20:15 UTC, instinct-it-academy commented on lesson-19-mvc/hashstorage.js
> +  this.object = object;
на сколько вижу Вы планировали передавать object в функции конструкторе как аргумент, но нигде не этого не делаете, если так - то не корректное поведение, вы не корректно сохраняете в localStorage

2022-04-21 20:15 UTC, instinct-it-academy commented on lesson-19-mvc/hashstorage.js
> +function TLocalStorage(object) {
данный функционал должен быть частью THashStorage, не должно быть необходимости создавать 2 отдельных хранилища

2022-04-21 20:19 UTC, instinct-it-academy requested changes
Установил не корректный статус предыдущего ревью, чтобы не изменять добавляю дополнительный комментарий с запросом на исправление комментариев

2022-04-25 06:56 UTC, DzmitryKhokha commented on lesson-19-mvc/hashstorage.js
> +function TLocalStorage(object) {
Исправил, проверьте пожалуйста

2022-05-28 20:22 UTC, instinct-it-academy approved these changes
Добрый вечер, принято

2022-05-28 20:22 UTC, merged