Lesson 3 code execution
DzmitryKhokha/js-hometasks-khokha pull request #2
Opened 2022-02-10 10:06 UTC by DzmitryKhokha

2022-02-13 11:03 UTC, instinct-it-academy requested changes
Добрый день, задание на небольшую доработку - попробуйте уйти от бесконечного цикла, сделать явную проверку в условиях цикла.

2022-02-13 11:03 UTC, instinct-it-academy commented on lesson-3-code-execution/task1.js
> +
не нужны пустые строки, по идее мы их добавляем только в случае необходимости улучшить читабельность кода. В данном случае достаточно просто отступов.

2022-02-13 11:03 UTC, instinct-it-academy commented on lesson-3-code-execution/task3.js
> +while (true) {
попробуйте перенести (number === '' || number === null || !isFinite(parseInt(number))) в условия цикла, т.е. уйти от бесконечного цикла

2022-02-13 11:03 UTC, instinct-it-academy commented on lesson-3-code-execution/task3.js
> +    if (number === '' || number === null || !isFinite(parseInt(number)))
пожалуйста оборачивайте в { } не пропускайте

2022-02-13 20:21 UTC, DzmitryKhokha commented on lesson-3-code-execution/task1.js
> +
Понял, будем исправляться)

2022-02-13 20:59 UTC, DzmitryKhokha commented on lesson-3-code-execution/task3.js
> +while (true) {
Внес изменения. Проверьте пожалуйста)

2022-02-26 21:12 UTC, instinct-it-academy approved these changes

2022-02-26 21:12 UTC, instinct-it-academy commented on lesson-3-code-execution/task3.js
> +} while (true)
на сколько вижу бесконечный цикл всё таки остался ) как вариант может быть, но обратите внимание на пример выполнения задания

2022-02-26 21:12 UTC, merged